services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      GENERIC_TIMEZONE: Europe/Brussels
      N8N_BASIC_AUTH_ACTIVE: "true"

    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
